### ISSUE TITLE
Bug on data breach, fix code coming soon

### ISSUE THREAD

**Issue by MakiniMakini** [collinsmuriuki/instagrm#1]
![Screen Shot 2020-05-05 at 5 31 03 PM](https://user-images.githubusercontent.com/61656724/81078220-9c15e100-8ef6-11ea-894a-0bb9c1edce45.png)
@collinsmuriuki

**Comment by collinsmuriuki** [comment]
Tolerable for this project

**Comment by MakiniMakini** [comment]
Noted, with thanks!
